# Generated by Django 3.2.4 on 2021-06-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='buildingNo',
            new_name='buildingNum',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street',
            new_name='mobileNum',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zone',
            new_name='streetNum',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='zoneNum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
